
GET http://localhost:10001/category HTTP/1.1
###
GET http://localhost:10001/cookingMethods
###
GET http://localhost:10001/cookingTips 
###
GET http://localhost:10001/product
###
GET http://localhost:10001/version
###
GET http://localhost:10001/category/1
###
GET http://localhost:10001/cookingMethods/1
###
GET http://localhost:10001/product/category/1
###
GET http://localhost:10001/product/1/name
###
GET http://localhost:10001/CookingTips/1
###
GET http://localhost:10001/product/1


